### ISSUE TITLE
NetworkControl : Setting route fails on DHCP server IP different from gateway

### ISSUE THREAD

**Issue by kuscsik** [rdkcentral/ThunderNanoServices#356]
Depending on server implementation DHCP ACK not necessarily contains a ROUTE option. RFC only states that options in ACK should not be in conflict with OFFER. If the route option is missing from ACK,  the **NetworkControl** plugin tries to set the GW to the DHCP address. If the Gateway address differs from the DHCP server address, this will fail and it results that the client has no internet connection.

**Comment by pwielders** [comment]
Hi @kuscsik 
Just to clarify, I assume that the default gateway was set and the network control now overwrites it with the DHCP Server as being the default gateway becuase it did not receive a router address and your issue occurs in this scenario?
Or are you looking for configuring a default router in the NetworkControl config.json that should be used if the DHCP does not offer a router IP address ?
For me both options could be feaible, in case the DHCP Server does not send a router address.

**Comment by kuscsik** [comment]
Hi @pwielders ,

the issue is with the DHCP client implementation and the problem manifest if the interface is set to dynamic with no particular static configuration. The problem is that the current implementation assumes that the DHCPACK holds the router option. It is a perfectly valid case when the DHCP Offer has the router info but it is excluded in DHCPACK. However, the current NetworkControl implementation will fail ignore the router option from the Offer leading to a broken network configuration.

**Comment by pwielders** [comment]
Hi @kuscsik 
I agree that what I found in the code (if there is no router option in the Offer, use the server that gave the Offer as being the gateway, https://github.com/rdkcentral/ThunderNanoServices/blob/master/NetworkControl/DHCPClient.h#L370-L373) is not good, and should be left to the higher layer.
So lets change it, but what I still do not understand is what you would expect. 
The options we could realilize  (and I think we could implement them all, and can be lected by configuration of the plugin)
1) Do nothing, too bad, no default gateway will be set.
2) Check if the default gateway is already defined, if so, do nothing -> end.
    If it is not defined, check if there is a default gateway configured in the config, if so set that one -> end.
    If there is no default defined and there is no defaulr gateway configured, use the source of the DHCP offer as the default gateway and set it.
Would that solve the issue ?

**Comment by kuscsik** [comment]
Hi @pwielders,

the client should look into the OFFER package and save the gateway if available for the case the route option is not available in the ACK package. The current implementation ignores the route option in the OFFER package.

**Comment by pwielders** [comment]
Oke. I think it is clear, will double check this with the dhcp protocol spec. Still I do think that we should not assume a DHCP Server address as the default gateway if gateway and router option is not set, but indeed check if a default route was already set and only use the DHCP Server IP adress if there is really no other alternative :-)

**Comment by pwielders** [comment]
Hi @kuscsik,
If I understand you correctly, if the route option is not supplied in the OFFER or the ACK, you should use the field giaddr field in the core message (https://github.com/rdkcentral/ThunderNanoServices/blob/master/NetworkControl/DHCPClient.h#L103) as the default router even if there is already a default gateway set?

**Comment by pwielders** [comment]
I do not think that the route option is ignored in the OFFER the options are parsed here: https://github.com/rdkcentral/ThunderNanoServices/blob/master/NetworkControl/DHCPClient.h#L744
and picked up/recorded (in the same file) on line 753 for the OFFER,and on line 766 for the ACK. So I do not think they are ignored.

**Comment by kuscsik** [comment]
Hi @pwielders,

   yes, the gateway  is attached to the offer but it doesn't affect the interface route table.  The actual update of the gateway happens at line 766 which takes the route option from the ACK packet parsed in line 744. The route from the OFFER is at this point discarded. I can provide you a DHCP pcap that is from a case where the issue is reproduced.

**Comment by pwielders** [comment]
Yes, clear. We will pick it up. A PCAP might be usefull, as I do not know if we can really test this. We will leave that up to you :-)

**Comment by pwielders** [comment]
@kuscsik What DHCP server are you using, that might be usefull to know on how we vcan reproduce it. Do think it is a bit strange that the options sets are different between OFFER and ACK

**Comment by HaseenaSainul** [comment]
Hi @kuscsik,
Could you please share me the value of frame.siaddr and OPTION_ROUTER:rInfo in your setup ?
For me OPTION_ROUTER:rInfo is available for both Offer and Ack. So I just added a check to validate option.gateway is valid before updating the _gateway (so Ack not sending case it will not override the one already shared through offer):
https://github.com/rdkcentral/ThunderNanoServices/commit/0fbb59a98cdef769be5e77838d55843875af5c69
Could you please check this work in your case ?

**Comment by HaseenaSainul** [comment]
Hi @kuscsik,
Could you please share me the details I asked ? I am trying to solve this issue :-)

**Comment by kuscsik** [comment]
Attaching pcap files. 
[gw_not_in_ack.pcap.zip](https://github.com/rdkcentral/ThunderNanoServices/files/6129090/gw_not_in_ack.pcap.zip)

**Comment by HaseenaSainul** [comment]
Thanks @kuscsik, will check, the https://github.com/rdkcentral/ThunderNanoServices/commit/0fbb59a98cdef769be5e77838d55843875af5c69 is still showing issue in your setup ? is this tested with above commit ?

**Comment by HaseenaSainul** [comment]
@kuscsik, I checked the shared pcap and found the differences. I already addressed this with the commit : https://github.com/rdkcentral/ThunderNanoServices/commit/0fbb59a98cdef769be5e77838d55843875af5c69, Are you able to test it ?

**Comment by kuscsik** [comment]
Hi,

unfortunately I don't have access to the problematic network, only the pcap files.

**Comment by HaseenaSainul** [comment]
Ok, please let us know once you able to get access and test

**Comment by pwielders** [comment]
Solved. Waiting for test-feedback!
