### ISSUE TITLE
WifiControl: SSID is not properly decoded

### ISSUE THREAD

**Issue by BriceLin-TTI** [rdkcentral/ThunderNanoServices#395]
If SSID contains non-ascii characters, they are converted to utf-8 and escaped to hexadecimal escape sequences.
In old RDK wifi-hal, this is unescaped by printf_decode provided by wpa_supplicant.

**Comment by pwielders** [comment]
A lot of changes have been made around encoding and escaping of JSON information. Expectation is that this resolved the issue at hand here. If not let us know the use case (a name of the SSID) that we can double check and fix it.
