### ISSUE TITLE
Documentation incorrect for SecurityAgent

### ISSUE THREAD

**Issue by kpears201** [rdkcentral/ThunderNanoServices#56]
There seems to be two READMEs for Security Agent
https://github.com/rdkcentral/ThunderNanoServices/blob/master/SecurityAgent/doc/SecurityAgentPlugin.md
Seems to not have documentation on the `acl` configuration parameter as well as docs around what the ACL file looks like.
https://github.com/rdkcentral/ThunderNanoServices/blob/master/SecurityAgent/SecurityAgentPlugin.md
Has documentation on ACL list, however the documentation is not correct. In the acl file it has the field `groups`, however it should be `assign`.
https://github.com/rdkcentral/ThunderNanoServices/blob/master/SecurityAgent/AccessControlList.h#L194
The example ACL json also has the wrong value `groups`
https://github.com/WebPlatformForEmbedded/ThunderNanoServices/blob/master/SecurityAgent/example_acl.json
It also might be helpful in the docs to say where the acl file should go. Looking into the source I was able to find out it is in the plugin's persistent path `/root/SecurityAgent`

**Comment by MFransen69** [comment]
Hi Kevin,

Thanks for reporting this. We have created an issue for it in our issue tracking system [here](https://jira.rdkcentral.com/jira/browse/METROL-108) and we'll make sure to pick it up when somebody becomes available depending on priority.

Best, Marcel

**Comment by woutermeek** [comment]
This is resolved in https://github.com/rdkcentral/rdkservices/pull/228, plugin is also moved to rdkcentral.
